# Generated by Django 5.1.6 on 2025-03-07 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory_Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('directory_type', models.CharField(choices=[('refusal_node', 'Узел отказа'), ('var_remaining', 'Способ восстановления')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Directory_TO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('factory_number', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('engine_number', models.CharField(max_length=255)),
                ('transmission_number', models.CharField(max_length=255)),
                ('drive_axle_number', models.CharField(max_length=255)),
                ('steerable_bridge_number', models.CharField(max_length=255)),
                ('delivery_contract', models.CharField(max_length=255)),
                ('date_shipment', models.DateTimeField(blank=True)),
                ('customer', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('equipment', models.TextField()),
                ('client', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Directory_Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('model_type', models.CharField(choices=[('machine_model', 'Модель техники'), ('engine_model', 'Модель двигателя'), ('transmission_model', 'Модель трансмиссии'), ('drive_axle_model', 'Модель ведущего моста'), ('steerable_bridge_model', 'Модель управляемого моста')], max_length=255)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory', to='silant_data.machine')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine', to='silant_data.service_company'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('operating_time', models.IntegerField()),
                ('refusal_description', models.TextField()),
                ('using_extra_components', models.CharField(max_length=255)),
                ('date_remaining', models.DateTimeField()),
                ('downtime', models.CharField(max_length=255)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='silant_data.directory_complaint')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silant_data.machine')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint', to='silant_data.service_company')),
            ],
        ),
        migrations.CreateModel(
            name='TO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_TO', models.DateTimeField(auto_now_add=True)),
                ('operating_time', models.IntegerField()),
                ('order_number', models.CharField(max_length=255)),
                ('date_order', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TO', to='silant_data.machine')),
                ('service_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TO', to='silant_data.service_company')),
                ('type_TO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TO', to='silant_data.directory_to')),
            ],
        ),
    ]
