# Generated by Django 5.1.6 on 2025-03-09 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='to',
            name='type_TO',
        ),
        migrations.AddField(
            model_name='directory_to',
            name='type_TO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='TO', to='silant_data.directory_to'),
            preserve_default=False,
        ),
    ]
