# Generated by Django 5.1.6 on 2025-03-10 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant_data', '0005_alter_directory_to_type_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directory_to',
            old_name='type_TO',
            new_name='num_TO',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='directory',
        ),
        migrations.AddField(
            model_name='directory_complaint',
            name='complaint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='directory_complaint', to='silant_data.complaint'),
            preserve_default=False,
        ),
    ]
