# Generated by Django 5.1.6 on 2025-03-10 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant_data', '0006_rename_type_to_directory_to_num_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='silant_data.machine'),
        ),
    ]
